name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DOTNET_SDK_VERSION: 10.0.401
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore
        run: dotnet msbuild _Development/Solution.proj /t:_Restore
      - name: Build
        run: dotnet msbuild _Development/Solution.proj /t:_Build /p:Configuration=Release
      - name: Test
        run: dotnet msbuild _Development/Solution.proj /t:_Test /p:Configuration=Release
      - name: Test summary
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Test summary
          path: _Development/obj/TestResults/*.trx
          reporter: dotnet-trx
          report-title: Tests
      - name: Test coverage summary
        run: |
          cat _Development/obj/TestReport/Summary.md | sed 's/# Summary/# Test coverage/g' >> $GITHUB_STEP_SUMMARY
  