name: Build
on: [push]
env:
  DOTNET_VERSION: 10.0.401
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet msbuild _Development/Solution.proj /t:_Restore
      - name: Build
        run: dotnet msbuild _Development/Solution.proj /t:_Build /p:Configuration=Release
      - name: Test
        run: dotnet msbuild _Development/Solution.proj /t:_Test /p:Configuration=Release
      - name: Test summary
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Test summary
          path: _Development/obj/TestResults/*.trx
          reporter: dotnet-trx
          report-title: Tests
      - name: Test coverage summary
        run: |
          cat _Development/obj/TestReport/Summary.md | sed 's/# Summary/# Test coverage/g' >> $GITHUB_STEP_SUMMARY
  # codeql:
  #   name: CodeQL
  #   runs-on: ubuntu-latest
  #   permissions:
  #     security-events: write
  #     packages: read
  #     actions: read
  #     contents: read
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: CodeQL Initialize
  #       uses: github/codeql-action/init@v4
  #       with:
  #         languages: csharp
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: ${{ env.DOTNET_VERSION }}
  #     - name: Restore
  #       run: dotnet msbuild _Development/Solution.proj /t:_Restore /p:Configuration=Release
  #     - name: Build
  #       run: dotnet msbuild _Development/Solution.proj /t:_BuildNoRestore /p:Configuration=Release
  #     - name: CodeQL Analyze
  #       uses: github/codeql-action/analyze@v4