name: Build
on: [push]
env:
  DOTNET_VERSION: 10.0.401
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore Solution.proj
        run: dotnet restore _Development/Solution.proj
      - name: Restore
        run: dotnet msbuild _Development/Solution.proj /t:_Restore /p:Configuration=Release
      - name: Build
        run: dotnet msbuild _Development/Solution.proj /t:_Build /p:Configuration=Release
      - name: Test
        run: dotnet msbuild _Development/Solution.proj /t:_Test /p:Configuration=Release
